version: '3'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn app:app --bind 0.0.0.0:5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  redis:
    image: redis
    ports:
      - "6379:6379"